### ISSUE TITLE
Opprette repo for automatiske tester

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/altinn2-tests#1]
Ta kopi av av 3.0 repo og se om vi får dette til å fungere.
Få bistand av Jeeva hvis nødvendig.

**Comment by jeevananthank** [comment]
@AinaEngen test koden fra AzureDevops er nå tilpasset for åpen kildekode og [merget ](https://github.com/Altinn/altinn2-tests/pull/2)inn. og ang. plassering av test data, må vi ta en beslutting .
