### ISSUE TITLE
Consent functional ConsentRequest

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn2-tests#16]
- [x] Approve a consent request

- [x] Reject an active consent request

- [x] Verify that consent has been logged as used

- [x] Verify that consent has been logged as used (REST)

- [x] Verify the consent has been deleted (REST)

- [x] Verify activity log for consent

- [x] Approve a fullmakt request

- [x] Reject an active fullmakt request

- [x] Verify activity log for fullmakt

- [x] Clean up -delete all consent requests

- [x] Delete an expired consent request

- [x] ConsentRequest with RedirectURL having Fragments

**Comment by anishastphen** [comment]
https://dev.azure.com/digdir/Altinn/_git/AutomatedPortalTest/pullrequest/6247

**Comment by anishastphen** [comment]
https://dev.azure.com/digdir/Altinn/_git/AutomatedPortalTest/pullrequest/6253
