### ISSUE TITLE
Testdata - replace all Altinn-pin testusers used i selenium tests with Tenor users

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn2-tests#85]
All Altinn pin users in Selenium regression tests must be replaced with Tenor users.  

- [x] Identify all Altinn pinusers in Selenium tests
- [x] Identify testcases which fix using Tenor users and determine which ones should be removed from selenium
- [x] Find Tenor users to replace Altinn pin users
- [x] Map all Altinn pin users with new Tenor users
- [x] Script to copy testdata from Altinn pin user to corresponding Tenor user

**Comment by rtafj** [comment]
@anishastphen  Feel free to add more info if needed:-)

**Comment by acn-Sneha** [comment]
@rtafj Siden Login med MinID er på i selenium da tenkte vi at å bruke MinID brukerne istedenfor TestID. Da lurer jeg at krever vi det fortsatt?

**Comment by acn-Sneha** [comment]
@ernstjonny @rtafj Har jeg laget de testcasene som vi skal ta bort og som vi trenger å fikse med MinID bruker

**Comment by acn-Sneha** [comment]
@rtafj @ernstjonny Jeg tror den tasken er ferdig med bytting Altinn pin bruker med Tenor testdata, men jeg ser testene feiler fortsatt som trenger en nye task. Da det kan lukkes og lager en nye task for å fikse de failing testsene.

**Comment by acn-Sneha** [comment]
@ernstjonny @rtafj @Siri-Anna  Lukker tasken siden vi krever ny task for å fikse testene i selenium :)
